### ISSUE TITLE
Pinnacle POI script not showing window for tx site on Pinnacle 16.2.1

### ISSUE THREAD

**Issue by mchamberland** [cutright/IMRT-QA-Data-Miner#21]
The windowing system has been overhauled in Pinnacle 16 (my version is 16.2.1) and running the Pinnacle POI script returns an error for [line 23 ](https://github.com/cutright/DVH-Analytics/blob/master/resources/Pinnacle%20Scripts/DVH-Analytics_Create-POIs.Script.p3rtp#L23) saying it's unable to create window "TempStoreEditor".

This error prevents you from typing in the name of the treatment site, so the POI just gets the name "tx: ".

Any idea? I've never had to deal with Pinnacle scripts before. Someone suggested that WindowList should be XtWindowList in Pinnacle 16, but that didn't work.

**Comment by mchamberland** [comment]
@cutright  If you don't know off the top of your head, I'll contact Philips / Pinnacle support.

**Comment by mchamberland** [comment]
Wait, it seems to sorta work. But it looks way different than it used to... 
![P16_storeEditor](https://user-images.githubusercontent.com/1675666/72563220-32a49080-387b-11ea-940a-a128e6c28bbf.jpg)

I guess that's fine?

**Comment by cutright** [comment]
I think you meant to post this over on DVH Analytics?

I don't have any experience with scripting in P16.  But since P16 stores rx information in DICOM now, might be easier to just create the TxSite POI manually?  Alternatively, DVHA assumes the plan name is your site by default.

You could also export your plans into folders by site, then just import one site at a time and check apply to all plans when you edit the site name.  And then just skip the script all together.

**Comment by mchamberland** [comment]
Yes, totally meant this for DVHA.

And these are all good ideas.
